services:
  - type: web
    name: hiconvert
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: MAX_CONTENT_LENGTH
        value: 20971520  # 20MB en bytes
    healthCheckPath: /
    disk:
      name: uploads
      mountPath: /uploads
      sizeGB: 1
    autoDeploy: false
    numInstances: 1
    plan: starter
